# Generated by Django 6.0.4 on 2026-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_field_id_alter_fieldupdate_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldupdate',
            name='stage_at_update',
            field=models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], max_length=20),
        ),
    ]
